#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Exit if the commit message file has any content aside from comments and whitespace
if grep -vE '^\s*#|^\s*$' "$COMMIT_MSG_FILE" | grep -q .; then
  exit 0
fi

# Run Commitizen
(exec < /dev/tty && node_modules/.bin/cz --hook) || true < /dev/null
